### PR TITLE
Docs changes

### PR DESCRIPTION
**Pull request by zvada**
* added links to troubleshooting docs
* added how to manually submit APEL records
* fixed formatting

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
That's at least 1 commit per line.  That's a lot of commits, but the final diff looks ok.

**Comment by zvada** [comment]
Yeah, I should be a better job on squashing a commits next time. Was lazy on that, there were commits from several weeks ago so wanted to get that merged asap. Thanks for review!

**Comment by bbockelm** [comment]
Actually, just go ahead and do a rebase / squash before the merge.

**Review by bbockelm — CHANGES_REQUESTED** [review]
Please squash.

**Pull request merged**
